### ISSUE TITLE
Remove console output

### ISSUE THREAD

**Issue by florian03-1** [xaviersolau/BlazorJsBlob#11]
It would be great if you can disable the console log in the javascript module... this is a great library and I want to use it in a production environment (and therefore this console outputs are confusing for the customer).

**Comment by xaviersolau** [comment]
Well, I will disable it be default.

**Comment by xaviersolau** [comment]
Available in [v1.0.2](https://www.nuget.org/packages/SoloX.BlazorJsBlob/1.0.2)
