### ISSUE TITLE
Not allowed to load local resource: blob:https://localhost:7297/30bbe78f-2ab8-4216-a201-e0cae6656437

### ISSUE THREAD

**Issue by ihavenokia** [xaviersolau/BlazorJsBlob#14]
I am using Blazor server and I need to show a pdf in a embed tag. I was porting a JS web page to blazor and I tried this nuget to achive that. Everything seems to work fine, but when the page tries to show the `blob.Uri`, it gives an error in the console:

Not allowed to load local resource: blob:https://localhost:7297/30bbe78f-2ab8-4216-a201-e0cae6656437

This is my HTML code:
`@if (blob != null)
    {
        <div>
            <embed src="@blob.Uri" width="500" height="500" type="@blob.Type">
        </div>
    }`

This is C#:

```
private IBlob blob;

private async Task LoadFiles(InputFileChangeEventArgs e)
{
   ...
   Stream stream = new MemoryStream(bytes);
   await using var Blob = await BlobService.CreateBlobAsync(stream, "application/pdf");
   blob = Blob;
   ...
}
```

Also, I added service to builder and injected in the page.

**Comment by xaviersolau** [comment]
I think that the Blob is disposed.
In your Load files you are using `await using var Blob` so as soon as the method returns the Blob is deleted.
You should consider instead to make your component disposable and to dispose the Blob only when your component is disposed.
Hope this helps.
